package com.example.greendaodemo.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendaodemo.entities.StudyPlanEntity;

import com.example.greendaodemo.greendao.dao.StudyPlanEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studyPlanEntityDaoConfig;

    private final StudyPlanEntityDao studyPlanEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studyPlanEntityDaoConfig = daoConfigMap.get(StudyPlanEntityDao.class).clone();
        studyPlanEntityDaoConfig.initIdentityScope(type);

        studyPlanEntityDao = new StudyPlanEntityDao(studyPlanEntityDaoConfig, this);

        registerDao(StudyPlanEntity.class, studyPlanEntityDao);
    }
    
    public void clear() {
        studyPlanEntityDaoConfig.clearIdentityScope();
    }

    public StudyPlanEntityDao getStudyPlanEntityDao() {
        return studyPlanEntityDao;
    }

}
